#!/bin/sh
PID=$$

make downloads/vnu/vnu.jar
bin/validate-server &
PID="$PID $!"

trap "kill $PID" 2 15
while sleep 1 ; do
  if make -q all >/dev/null 2>&1; then
    true
  else
    make check-clean
    until make -q all >/dev/null 2>&1; do
      make all
    done
  fi

  until make -q check >/dev/null 2>&1; do
    make check
  done
done
